apiVersion: v1
kind: Service
metadata:
  labels:
    app: title
  name: title-service
  namespace: gitlab-kubernetes-agent
spec:
  selector:
    app: title-service
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
